return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	version = "*",
	event = { "BufReadPost", "BufNewFile", "BufWritePre" },
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	opts = {
		symbols = {
			separator = ">",
		},
		kinds = {
			File = "",
			Module = "",
			Namespace = "",
			Package = "",
			Class = "",
			Method = "",
			Property = "",
			Field = "識",
			Constructor = "",
			Enum = "",
			Interface = "蘒",
			Function = "ƒ",
			Variable = "",
			Constant = "",
			String = "",
			Number = "",
			Boolean = "⊨",
			Array = "",
			Object = "⦿",
			Key = "⊛",
			Null = "",
			EnumMember = "",
			Struct = "פּ",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
	},
}
